[package]
name = "open-cypher"
version = "0.1.1"
edition = "2021"
authors = ["Austin Poor <code@austinpoor.com"]
description = "A rust library for parsing openCyper queries."
documentation = "https://docs.rs/open-cypher"
readme = "README.md"
homepage = "https://github.com/a-poor/open-cypher"
repository = "https://github.com/a-poor/open-cypher"
license = "MIT"
keywords = ["sql", "cypher", "graph", "parser"]
categories = ["parser-implementations"]

[dependencies]
bet = "1.0.2"
pest = "2.0"
pest_derive = "2.0"
regex = "1.8.1"

